### ISSUE TITLE
random walk sampling stuck - scale hitting 0.0

### ISSUE THREAD

**Issue by villrv** [joshspeagle/dynesty#85] opened 2018-03-02 15:43 UTC
Have been running dynesty with mosfit and receive the following error before convergence:

"RuntimeError: The random walk sampling is stuck! Some useful output quantities:...."

due to the scale hitting 0.0. Is there a way to avoid this issue?

**Comment by joshspeagle** [comment] 2018-03-03 00:28
This is the first time I've seen this issue arise with the random walk sampler. Can you send me the exact outputs from this or the code/seed you used that produced this result? And is this with the most recent version of `dynesty` (v0.9.1)?

**Comment by joshspeagle** [comment] 2018-03-07 18:36
@villrv and I weren't able to consistently reproduce this issue under the same conditions, so I'm closing this for now. We can come back to it if it continues to be a problem.

**Comment by joshspeagle** [comment] 2018-03-17 00:08
After some debugging with help from @guillochon, it looks like this is a problem where the likelihood "slams" against the bounds of the unit cube in >=1 dimension of the fit. I'll try and work on a fix to deal with this issue ASAP.

**Comment by joshspeagle** [comment] 2018-03-21 17:00
This seems to have been mostly resolved, so I'm re-closing this issue for now barring something catastrophic.

**Closed by joshspeagle** 2018-03-21 17:00 UTC
