### ISSUE TITLE
live point's likelihood not valid

### ISSUE THREAD

**Issue by npassaleva** [joshspeagle/dynesty#453] opened 2023-09-29 14:55 UTC
Dynesty version: 2.1.2

SETUP:
with MPIPool() as pool:
                        if not pool.is_master():
                            pool.wait()
                            sys.exit(0)

                        dsampler = dynesty.NestedSampler(lnlike, log_prior_nested, ndim=ndim,
                                                    bound='multi', sample='unif', rstate=rstate, pool=pool)
                        dsampler.run_nested(checkpoint_file=dir_out+dynestysave)

Hi my dynesty sampling is stopping because the of the error: "The log-likelihood of live point is invalid". I was wondering how I can overcome this problem. I've already launched my code with the same likelihood but different data set and it works so I can't figured out which is the problem. 
Thank you

**Comment by segasai** [comment] 2023-09-29 16:55
Please follow the template how to report issues
https://github.com/joshspeagle/dynesty/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by npassaleva** [comment] 2023-09-30 14:25
I apologize, is it now correct?

**Comment by segasai** [comment] 2023-10-02 11:34
Thanks
The error means that your likelihood returns values that either +Inf or NaN which is not allowed.

**Comment by npassaleva** [comment] 2023-10-02 12:13
Is there a way to check the values of the parameters that produce these results?

**Comment by segasai** [comment] 2023-10-02 13:24
i would suggest inserting print statements inside your function.

**Comment by segasai** [comment] 2023-10-03 21:58
closing as not a bug

**Closed by segasai** 2023-10-03 21:58 UTC
Labels: question
