### ISSUE TITLE
ellipsoid self modification

### ISSUE THREAD

**Issue by bd-j** [joshspeagle/dynesty#17] opened 2017-05-09 18:30 UTC
It might be cleaner to put the logic in `bounding_ellipsoids` for generating the ellipsods into the ellipsoids themselves (as a method).  So you could supply points and pointvol to this method and the ellipsoid would update itself (instead of having to instantiate a new Ellipsoid each time)

**Comment by joshspeagle** [comment] 2017-05-11 00:39
Started working on this, and then realized that while this might be fine for a single `Ellipsoid`, the number of ellipsoids generated by `bounding_ellipsoids` (and `_bounding_ellipsoids`) is not fixed by design. This poses a problem for allowing internal updates in `MultiEllipsoid`, since we'll need to initialize new `Ellipsoid` objects anyways. While we could get around this with extra bookkeeping (adding ellipsoids to a list, updating them as we go, making them as "dead" when we want to ignore them, and appending new ones as we need them), I don't think this translates cleanly into self-modification.

I think I can still add in a `bound` method for the two classes though to allow them to be instantiated once and then be modified by users.

**Comment by bd-j** [comment] 2017-05-11 12:22
ok, not worth much effort if it's not easy as there's no actual new functionality.

**Closed** 2017-05-11 23:39 UTC
