### ISSUE TITLE
Dynamic Nested Sampler: No Bounds?

### ISSUE THREAD

**Issue by bacook17** [joshspeagle/dynesty#32] opened 2017-06-19 14:39 UTC
When running dynamic nested sampler, it failed (presumably after completing its inner loop), with the following message:
`run: 0 | iter: 1513 | nc: 1 | ncall: 51328 | eff(%):  2.950 | logz: -7727.260 +/-  0.227 | dlogz: 13.417 >  0.500
run: 0 | iter: 1514 | nc: 1 | ncall: 51329 | eff(%):  2.952 | logz: -7716.199 +/-  0.660 | dlogz:  2.083 >  0.500
run: 0 | iter: 1515 | nc: 1 | ncall: 51330 | eff(%):  2.953 | logz: -7714.875 +/-    nan | dlogz:  0.660 >  0.500    Traceback (most recent call last):
  File "pcmd_integrate.py", line 55, in <module>
    results = fit_model.nested_integrate(**args)
  File "/n/home01/bcook/pixcmd/pcmdpy/fit_model.py", line 202, in nested_integrate
    sampler.run_nested(ninit=N_points, maxcall_init=max_call, dlogz_init=dlogz)
  File "/n/home01/bcook/dynesty/dynesty/dynamicsampler.py", line 1121, in run_nested
    logl_bounds = wt_function(res, wt_kwargs)
  File "/n/home01/bcook/dynesty/dynesty/dynamicsampler.py", line 82, in weight_function
    bounds = (min(bounds) - lpad, min(max(bounds) + lpad, nsamps - 1))
ValueError: min() arg is an empty sequence
`

It seems like, for some reason, the default weight function is not finding any "bounds", in dynamicsampler.py line 81:

`    bounds = np.arange(nsamps)[weight > maxfrac * max(weight)]
`

**Comment by joshspeagle** [comment] 2017-07-23 04:58
I couldn't reproduce this exact issue, but since this was raised I realized there were several issues with the dynamic sampler that could have led to incorrect results. These included problems with the weight function as well as behavior within the dynamic sampler itself. Hopefully this should be fixed. I'm tentatively closing this for now but might reopen this if it comes up again.

**Closed by joshspeagle** 2017-07-23 04:58 UTC
